name: Audit STAGING
on: 
  repository_dispatch:
    types: [deploy-triggered-audit]

jobs:
  audit:
    name: Lighthouse audit
    runs-on: ubuntu-latest
    steps:
    - name: Audit
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://nevskii-web.herokuapp.com/'
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: report
        path: './report'
  publish:
    name: Publish audit to S3
    needs: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: report
          path: report
      - name: Upload to S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.NEVSKII_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.NEVSKII_AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --recursive \
          --acl public-read \
          ./report s3://nevskii/audit
