name: Deploy STAGING
on: [pull_request, workflow_dispatch]

jobs:
  api:
    name: deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy nevskii-API
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'nevskii-api'
          heroku_email: ${{secrets.HEROKU_API_KEY}}
        env:
          HD_APP_BASE: 'packages/api'
      - name: Deploy nevskii-WEB
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'nevskii-web'
          heroku_email: ${{secrets.HEROKU_API_KEY}}
        env:
          HD_APP_BASE: 'packages/web'
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GHACTIONS_REPO_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-lighthouse-audit
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
