name: Deploy to Heroku

on: [push]

jobs:
  api:
    name: deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy nevskii-api Heroku app
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'nevskii-api'
          heroku_email: ${{secrets.HEROKU_API_KEY}}
        env:
          HD_APP_BASE: 'packages/api'
  web:
    name: deploy WEB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy nevskii-web Heroku app
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'nevskii-web'
          heroku_email: ${{secrets.HEROKU_API_KEY}}
        env:
          HD_APP_BASE: 'packages/web'
